name: flutter_form_validators
description: A Result<T, E> type for elegant error handling in Dart without try/catch.
version: 1.0.0
repository: https://github.com/farhana-95/flutter_form_validators
homepage: https://github.com/farhana-95/flutter_form_validators

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
